// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdu-r0bVIbp6nMiwlPlxzI00nWuoRktSQ',
    appId: '1:91870534065:web:f5c639ff37f204c9178590',
    messagingSenderId: '91870534065',
    projectId: 'moment-aad8b',
    authDomain: 'moment-aad8b.firebaseapp.com',
    storageBucket: 'moment-aad8b.firebasestorage.app',
    measurementId: 'G-PVVM1FE4SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-K-Y3NOw17eMH7KU5RV0BLqiy9EI1-E',
    appId: '1:91870534065:android:3740f90e356ab7be178590',
    messagingSenderId: '91870534065',
    projectId: 'moment-aad8b',
    storageBucket: 'moment-aad8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkdQfxf9gsfXYTQL8Z8PadHsncvWYw3HI',
    appId: '1:91870534065:ios:cc58b3cb11b4e26f178590',
    messagingSenderId: '91870534065',
    projectId: 'moment-aad8b',
    storageBucket: 'moment-aad8b.firebasestorage.app',
    iosBundleId: 'com.moment.mobile',
  );
}
